services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Auxmoney\OpentracingMonologBundle\Processor\MonologTracingHeaderProcessor:
    tags:
      - { name: monolog.processor }
